In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Dataset/processed/zomato_featured.csv")

In [2]:
df.shape[0]

51609

In [3]:
df["name"].nunique()

8792

In [4]:
df[["name","rate"]].sort_values(
    by="rate",
    ascending=False
).head(10)

                                 name  rate
3918      Byg Brewski Brewing Company   4.9
49522     Byg Brewski Brewing Company   4.9
36599  Asia Kitchen By Mainland China   4.9
32353  Asia Kitchen By Mainland China   4.9
20249  Asia Kitchen By Mainland China   4.9
5802           Belgian Waffle Factory   4.9
6738                         Flechazo   4.9
38368          Belgian Waffle Factory   4.9
29481  Asia Kitchen By Mainland China   4.9
42960          Belgian Waffle Factory   4.9

In [5]:
df[["name","votes"]].sort_values(
    by="votes",
    ascending=False
).head(10)

                              name  votes
49067  Byg Brewski Brewing Company  16832
49522  Byg Brewski Brewing Company  16832
49954  Byg Brewski Brewing Company  16832
4797   Byg Brewski Brewing Company  16345
4940   Byg Brewski Brewing Company  16345
3918   Byg Brewski Brewing Company  16345
18583                         Toit  14956
19205                         Toit  14956
36583                     Truffles  14726
35916                     Truffles  14723

In [6]:
df["location"].value_counts().head(10)

location
BTM                      5109
HSR                      2521
Koramangala 5th Block    2502
JP Nagar                 2234
Whitefield               2140
Indiranagar              2075
Jayanagar                1926
Marathahalli             1843
Bannerghatta Road        1628
Bellandur                1283
Name: count, dtype: int64

In [7]:
df.groupby("location")["rate"]\
.mean()\
.sort_values(ascending=False)\
.head(10)

location
Lavelle Road             4.140871
Koramangala 3rd Block    4.020526
St. Marks Road           4.017201
Koramangala 5th Block    4.005870
Church Street            3.990976
Sankey Road              3.965385
Koramangala 4th Block    3.918668
Cunningham Road          3.900633
Residency Road           3.861960
MG Road                  3.855185
Name: rate, dtype: float64

In [8]:
df.groupby("location")["approx_cost"]\
.mean()\
.sort_values(ascending=False)\
.head(10)

location
Sankey Road         2505.555556
Race Course Road    1309.352518
Lavelle Road        1307.046332
MG Road             1156.215006
Infantry Road       1060.666667
Residency Road       964.083458
Langford Town        883.333333
St. Marks Road       871.306818
Cunningham Road      865.204082
Church Street        834.982332
Name: approx_cost, dtype: float64

In [9]:
df["cuisines"].value_counts().head(10)

cuisines
North Indian                           2907
North Indian, Chinese                  2381
South Indian                           1826
Biryani                                 915
Bakery, Desserts                        910
Fast Food                               801
Desserts                                760
Cafe                                    755
South Indian, North Indian, Chinese     726
Bakery                                  651
Name: count, dtype: int64

In [10]:
df.groupby("cuisines")["rate"]\
.mean()\
.sort_values(ascending=False)\
.head(10)

cuisines
Healthy Food, Salad, Mediterranean                                       4.900000
Asian, Chinese, Thai, Momos                                              4.900000
Continental, North Indian, Italian, South Indian, Finger Food            4.900000
Asian, Mediterranean, North Indian, BBQ                                  4.800000
Continental, North Indian, Chinese, European, BBQ, Finger Food, Asian    4.800000
North Indian, European, Mediterranean, BBQ                               4.800000
European, Mediterranean, North Indian, BBQ                               4.789474
American, Tex-Mex, Burger, BBQ, Mexican                                  4.750000
Continental, European, BBQ, Chinese, Asian                               4.700000
Chinese, American, Continental, Italian, North Indian                    4.700000
Name: rate, dtype: float64

In [11]:
df["rate"].mean()

np.float64(3.700141861024285)

In [12]:
df["Rating_Category"].value_counts()

Rating_Category
Good         18142
Average      10986
Excellent     9184
Poor          3278
Name: count, dtype: int64

In [13]:
df[df["Highly_Rated"]=="Yes"].shape[0]

12364

In [14]:
df["approx_cost"].mean()

np.float64(555.1706817516824)

In [15]:
df["Price_Category"].value_counts()

Price_Category
Mid-Range    21894
Budget       18515
Premium      10856
Name: count, dtype: int64

In [16]:
df[df["Premium_Restaurant"]=="Yes"].shape[0]

6889

In [17]:
df["votes"].mean()

np.float64(283.28336142920807)

In [18]:
df.nlargest(
    10,
    "Popularity_Score"
)[["name","Popularity_Score"]]

                              name  Popularity_Score
49067  Byg Brewski Brewing Company             47.68
49522  Byg Brewski Brewing Company             47.68
49954  Byg Brewski Brewing Company             47.68
3918   Byg Brewski Brewing Company             47.54
4797   Byg Brewski Brewing Company             47.54
4940   Byg Brewski Brewing Company             47.54
18583                         Toit             45.18
19205                         Toit             45.18
40415    AB's - Absolute Barbecues             45.13
41433    AB's - Absolute Barbecues             45.13

In [19]:
df["online_order"].value_counts()

online_order
Yes    30361
No     21248
Name: count, dtype: int64

In [20]:
df["book_table"].value_counts()

book_table
No     45193
Yes     6416
Name: count, dtype: int64

In [21]:
df["Service_Type"].value_counts()

Service_Type
Online Focused     26578
Basic Service      18615
Full Service        3783
Dine-In Focused     2633
Name: count, dtype: int64

In [22]:
df["Multi_Cuisine"].value_counts()

Multi_Cuisine
Yes    39187
No     12422
Name: count, dtype: int64

In [23]:
df.isnull().sum()

name                       0
location                  21
cuisines                  45
rest_type                227
online_order               0
book_table                 0
rate                   10019
votes                      0
approx_cost              344
listed_in_type             0
listed_in_city             0
Price_Category           344
Rating_Category        10019
Popularity_Category        0
Service_Type               0
Cuisine_Count              0
Popularity_Score       10019
Cost_per_Vote          10242
Multi_Cuisine              0
Premium_Restaurant         0
Highly_Rated               0
dtype: int64

# Key Findings

- Identified the locations with the highest restaurant concentration.
- Analyzed customer ratings and restaurant popularity.
- Compared pricing across restaurant segments and locations.
- Identified the most popular cuisines in Bangalore.
- Evaluated customer engagement using votes and popularity score.
- Examined the adoption of online ordering and table booking services.
- Generated business insights that will be visualized in the next notebook.